title: Hyunsu
author: Hyunsu Joo
email: hyunsujoo0609@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  ğŸ‘‹ ì•ˆë…•í•˜ì„¸ìš”. ì‚¬ìš©ì ì¤‘ì‹¬ìœ¼ë¡œ ìƒê°í•˜ê³  ì‚¬ìš©ìì˜ ìš”êµ¬ë¥¼ ê²½ì²­í•˜ëŠ” í”„ë¡ íŠ¸ì—”ë“œ ë””ë²¨ë¡œí¼ ì£¼í˜„ìˆ˜ ì…ë‹ˆë‹¤. ì´ ë¸”ë¡œê·¸ì—ëŠ” ì €ì˜
     ì†”ì§í•˜ê³  ì§„ì†”í•œ ê°œë°œ ê³µë¶€ ì´ì•¼ê¸°ë“¤ì„ ë‹´ì•˜ìŠµë‹ˆë‹¤.
show_excerpts: false # set to true to show excerpts on the homepage
paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag


# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: https-sooster910-github-io
  

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
  
    - url: https://www.linkedin.com/in/hyunsu-joo/
      icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>
      color: indigo

    - url: https://github.com/sooster910
      icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      color: indigo
   

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash
url: https://sooster910.github.io
source_url : https://github.com/sooster910/blogV2
production_url: https://sooster910.github.io/
destination: ./output/
#syntax highlighter
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
#Travis-CI setting
username: sooster910
repo: blogV2

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

exclude:
 - _posts/2021-01-01-react-codeSplitting.md
 - _posts/2020-11-1-Nodejs1.md
 - _posts/2020-10-10-algo-twosum.md
 - _posts/2020-03-01-react-render-series.md
 - _posts/2020-10-15-travisCI.md
 - _posts/2020-10-04-socketio.md
 - _posts/2020-11-01-socketio2.md
 - _posts/2020-10-20-passport.md
 - _posts/2020-10-05-cluster.md
 - _posts/2020-10-23-webpack.md
 - _posts/2020-12-01-linkedList.md
 - _posts/2021-05-13-last-december.md

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain

#Google Analytics
googleAnalytics:
  # provider : "google-gtag", 
  tracking_id :  "UA-197952130-1"
  measurement_id  : "G-NK1MYVRDXR"
 
  # anonymize_ip  : false
  # stream_id: : "2623351309"